"""Schemas module - Pydantic models for request/response validation."""

from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
    UserInfo,
    LoginResponse,
    LogoutResponse,
    PasswordChangeRequest,
    PasswordChangeResponse,
    CurrentUserResponse,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserResponse,
    UserListResponse,
    RoleBase,
    RoleResponse,
    RoleListResponse,
)
from app.schemas.audit import (
    AuditLogBase,
    AuditLogResponse,
    AuditLogFilterRequest,
    AuditLogListResponse,
    AuditLogStats,
)
from app.schemas.client import (
    ClientBase,
    ClientCreate,
    ClientUpdate,
    ClientResponse,
    ClientListResponse,
)
from app.schemas.employee import (
    SkillBase,
    SkillCreate,
    SkillResponse,
    EmployeeSkillInfo,
    EmployeeBase,
    EmployeeCreate,
    EmployeeUpdate,
    EmployeeResponse,
    EmployeeListResponse,
    EmployeeBulkImport,
    EmployeeBulkImportResult,
    EmployeeRecommendation,
)
from app.schemas.inquiry import (
    InquiryActivityBase,
    InquiryActivityCreate,
    InquiryActivityResponse,
    InquiryBase,
    InquiryCreate,
    InquiryUpdate,
    InquiryResponse,
    InquiryDetailResponse,
    InquiryListResponse,
    InquiryConvertRequest,
    InquiryStats,
)
from app.schemas.task import (
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskAssignmentCreate,
    TaskAssignmentResponse,
    TaskResponse,
    TaskListResponse,
    AITaskGenerationRequest,
    AIGeneratedTask,
    AITaskGenerationResponse,
    AIEmployeeRecommendationRequest,
    AIEmployeeRecommendation,
    AIEmployeeRecommendationResponse,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "UserInfo",
    "LoginResponse",
    "LogoutResponse",
    "PasswordChangeRequest",
    "PasswordChangeResponse",
    "CurrentUserResponse",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserResponse",
    "UserListResponse",
    "RoleBase",
    "RoleResponse",
    "RoleListResponse",
    # Audit
    "AuditLogBase",
    "AuditLogResponse",
    "AuditLogFilterRequest",
    "AuditLogListResponse",
    "AuditLogStats",
    # Client
    "ClientBase",
    "ClientCreate",
    "ClientUpdate",
    "ClientResponse",
    "ClientListResponse",
    # Employee
    "SkillBase",
    "SkillCreate",
    "SkillResponse",
    "EmployeeSkillInfo",
    "EmployeeBase",
    "EmployeeCreate",
    "EmployeeUpdate",
    "EmployeeResponse",
    "EmployeeListResponse",
    "EmployeeBulkImport",
    "EmployeeBulkImportResult",
    "EmployeeRecommendation",
    # Inquiry
    "InquiryActivityBase",
    "InquiryActivityCreate",
    "InquiryActivityResponse",
    "InquiryBase",
    "InquiryCreate",
    "InquiryUpdate",
    "InquiryResponse",
    "InquiryDetailResponse",
    "InquiryListResponse",
    "InquiryConvertRequest",
    "InquiryStats",
    # Task
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskAssignmentCreate",
    "TaskAssignmentResponse",
    "TaskResponse",
    "TaskListResponse",
    "AITaskGenerationRequest",
    "AIGeneratedTask",
    "AITaskGenerationResponse",
    "AIEmployeeRecommendationRequest",
    "AIEmployeeRecommendation",
    "AIEmployeeRecommendationResponse",
]
